---
- hosts: ubuntu
  become: true
  pre_tasks:

  - name: Update Repository Index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
  
- name: install elk
  hosts: ubuntu
  become: true
  roles:
    - elk
    
- name: install prometheus, grafana, influxdb
  hosts: ubuntu
  become: yes
  roles:
  - prometheus
  - grafana
  - influxdb

- name: install lamp
  hosts: ubuntu
  become: yes
  become_method: sudo
  vars_files:
    - vars/default.yml
  roles:
    - apache_and_php
    - mariadb

- name: install nagios
  hosts: ubuntu
  become: yes
  roles:
  - nagios
