---
- hosts: ubuntu
  become: true
  pre_tasks:

  - name: Update Repository Index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
  
- hosts: ubuntu
  become: true
  roles:
    - elk
